namespace SyntaxAnalysis
{
    public enum Nodes
    {
        Const,
        RefVar,
        RefFunc,
        Addition,
        Substraction,
        Multiplication,
        Division,
        Modulo,
        Negative,
        AreEqual,
        AreNotEqual,
        LowerThan,
        GreaterThan,
        LowerOrEqual,
        GreaterOrEqual,
        And,
        Or,
        Not,
        Assign,
        Block,
        Condition,
        Declaration,
        Drop,
        Out,
        Loop,
        Break,
        Continue
    }
}
